// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HipHopPizzaWangs.Migrations
{
    [DbContext(typeof(HipHopPizzaWangsDbContext))]
    partial class HipHopPizzaWangsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HipHopPizzaWangs.Modles.Item", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carrot",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orange",
                            OrderId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lemon",
                            OrderId = 3
                        });
                });

            modelBuilder.Entity("HipHopPizzaWangs.Modles.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("Feedback")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderTotal")
                        .HasColumnType("integer");

                    b.Property<string>("OrderType")
                        .HasColumnType("text");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "demoney@gmail.com",
                            CustomerName = "Dustin",
                            CustomerPhoneNumber = "9312613939",
                            Feedback = false,
                            IsOpen = false,
                            OrderTotal = 123,
                            OrderType = "Call in",
                            PaymentTypeId = 1,
                            Tip = 12,
                            UserId = "waefaw"
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "demoney@gmail.com",
                            CustomerName = "Dustin",
                            CustomerPhoneNumber = "9312613939",
                            Feedback = true,
                            IsOpen = true,
                            OrderTotal = 123,
                            OrderType = "Take Out",
                            PaymentTypeId = 2,
                            Tip = 12,
                            UserId = "waefaw"
                        },
                        new
                        {
                            Id = 3,
                            CustomerEmail = "demoney@gmail.com",
                            CustomerName = "Dustin",
                            CustomerPhoneNumber = "9312613939",
                            Feedback = false,
                            IsOpen = true,
                            OrderTotal = 123,
                            OrderType = "Dine In",
                            PaymentTypeId = 3,
                            Tip = 12,
                            UserId = "waefaw"
                        });
                });

            modelBuilder.Entity("HipHopPizzaWangs.Modles.Payment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentType = "Visa"
                        },
                        new
                        {
                            Id = 2,
                            PaymentType = "MasterCard"
                        },
                        new
                        {
                            Id = 3,
                            PaymentType = "Amex"
                        });
                });

            modelBuilder.Entity("HipHopPizzaWangs.Modles.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CashierEmail")
                        .HasColumnType("text");

                    b.Property<string>("CashierPassword")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "waefaw",
                            CashierEmail = "demansell2016@gmail.com",
                            CashierPassword = "M@chelle2030"
                        },
                        new
                        {
                            Id = "wawfwaeufoaewfhaew",
                            CashierEmail = "Trex@gmail.com",
                            CashierPassword = "M@chelle2012"
                        },
                        new
                        {
                            Id = "waeabasjvajsvjka",
                            CashierEmail = "Tricertops@gmail.com",
                            CashierPassword = "M@chelle2020"
                        });
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("ItemsId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("ItemOrder");
                });

            modelBuilder.Entity("HipHopPizzaWangs.Modles.Order", b =>
                {
                    b.HasOne("HipHopPizzaWangs.Modles.Payment", "Payment")
                        .WithMany("Order")
                        .HasForeignKey("PaymentId");

                    b.HasOne("HipHopPizzaWangs.Modles.User", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItemOrder", b =>
                {
                    b.HasOne("HipHopPizzaWangs.Modles.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HipHopPizzaWangs.Modles.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HipHopPizzaWangs.Modles.Payment", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("HipHopPizzaWangs.Modles.User", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
